In [1]:
import pandas as pd
import numpy as np

In [2]:
#读取excel数据
#定义路径IO
IO = r'C:\Users\lirong1\Desktop\会员日复盘\data_prime_day.xlsx'
spider = pd.read_excel(io = IO,sheet_name=0,header=0,index_col= 0)
spider[:5]

,create_time,shop_name,coupon,price,review,star,ask_num,category,category_rank,sub_category,sub_category_rank
asin,,,,,,,,,,,
B08KH59H1C,14/10/2020 00:25:58,tangkula,0.0,229.99,11,4.4,3,Video Projection Screens,438,Nix,0
B08K8N2BFT,14/10/2020 00:26:58,tangkula,10.0,189.99,11,4.4,3,Video Projection Screens,1342,Nix,0
B0832D58GP,14/10/2020 02:17:30,tangkula,7.0,139.99,11,4.4,3,Video Projection Screens,172,Nix,0
B081RY8S6H,14/10/2020 02:26:52,superbuy,0.0,37.99,63,4.5,0,Camera Cases,411,Nix,0
B081RY5HV3,14/10/2020 02:26:56,superbuy,0.0,69.99,63,4.5,0,Camera Cases,411,Nix,0

In [3]:
promising_asin = pd.read_excel(io = IO,sheet_name=1,header=0,index_col= 0)
promising_asin[:5]

           shop_name  performance  impression  click  spend   sales
asin
B0172W2D6M  tangkula     5.454545       99922    965  38125  326576
B01M641PUR  tangkula     3.600000      136578    515  22990  241967
B01MUICHSX  tangkula     3.818182       89941    343  11611   90985
B01N0XMGQT  tangkula     3.882353      104837    427  32649  337778
B01N25WLAG  tangkula     4.285714       24924    162   6554  108988

In [4]:
##转换数据格式,转换为数值型后面使用聚合函数就不会报错了
# 归类不同字段类型
spider_fieldtype_str = ['shop_name','category','sub_category']
spider_fieldtype_int = ['ask_num','category_rank','sub_category_rank']
spider_fieldtype_float = ['coupon','price','star','review']
spider_fieldtype_time = ['create_time']

asin_fieldtype_str = ['shop_name']
asin_fieldtype_int = ['impression','click','spend','sales']
asin_fieldtype_float = ['performance']

# 清洗spider表的数据类型
for i in spider_fieldtype_str:
    spider['{}'.format(i)] = spider['{}'.format(i)].astype(str)
    

for i in spider_fieldtype_int:
    spider['{}'.format(i)] = spider['{}'.format(i)].astype(int)
    
    
for i in spider_fieldtype_float:
    spider['{}'.format(i)] = spider['{}'.format(i)].astype(float)
    
    
for i in spider_fieldtype_time:
    spider['{}'.format(i)] = pd.to_datetime(spider['{}'.format(i)])
    
    
#清洗promising_asin表的数据类型    
for i in asin_fieldtype_str:
    promising_asin['{}'.format(i)] = promising_asin['{}'.format(i)].astype(str)
    
    
for i in asin_fieldtype_int:
    promising_asin['{}'.format(i)] = promising_asin['{}'.format(i)].astype(int)
    
    
for i in asin_fieldtype_float:
    promising_asin['{}'.format(i)] = promising_asin['{}'.format(i)].astype(float)

In [5]:
#处理spider数据表,group by后求平均
spider_g = spider.groupby([spider.index,'category','sub_category'])['review','ask_num','category_rank','sub_category_rank','coupon','price','star'].mean()
spider_g[:5]

<ipython-input-5-6be2fa77afc6>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  spider_g = spider.groupby([spider.index,'category','sub_category'])['review','ask_num','category_rank','sub_category_rank','coupon','price','star'].mean()

,,,review,ask_num,category_rank,sub_category_rank,coupon,price,star
asin,category,sub_category,,,,,,,
B00LVG2QDQ,Home & Kitchen,Nix,0.0,0.0,4625421.5,0.0,0.0,0.00,0.0
B00LVG39FA,Patio Lawn & Garden,Nix,77.0,0.0,262859.5,0.0,0.0,89.99,4.0
B00LVG3B80,Patio Lawn & Garden,Nix,77.0,0.0,262859.5,0.0,0.0,89.99,4.0
B00M0HBIHA,Sports & Outdoors,Nix,810.0,84.0,23770.5,0.0,0.0,109.99,4.7
B00M0HBKQO,Sports & Outdoors,Nix,810.0,84.0,23770.5,0.0,0.0,99.99,4.7

In [6]:
##写码过程中用来测试的,不用管
##promising_asin.index.get_level_values('asin')[0]
#t1 = spider_g.iloc[spider_g.index.get_level_values('asin') == 'B00NCOZ9U2'].index.get_level_values('category')[0]
#t2 = spider_g.iloc[spider_g.index.get_level_values('asin') == 'B00NCOZ9U2'].index.get_level_values('sub_category')[0]
#spider_g.loc[('B00NCOZ9U2',t1,t2),'sub_category_rank']
#promising_asin.index.get_level_values('asin')
#perfect_table = pd.DataFrame(columns=['asin','shop_name', 'performance', 'impression','click','spend','sales','price','coupon','category','category_rank','sub_category','sub_category_rank','review','star','ask_num'])

In [7]:
##构建最终的完整大表
perfect_table = pd.DataFrame(columns=['asin','shop_name', 'performance', 'impression','click','spend','sales','price','coupon','category','category_rank','sub_category','sub_category_rank','review','star','ask_num'])
manual_needed = np.setdiff1d(promising_asin.index,spider_g.index.get_level_values('asin'))#asin在promising_asin中有在spider_g(爬虫数据库)中却没有的
for i in promising_asin.index.get_level_values('asin'):
    temp = {}
    if i in manual_needed:
        temp['asin'] = i
        temp['shop_name'] = promising_asin.loc[i]['shop_name']
        temp['performance'] = promising_asin.loc[i]['performance']
        temp['impression'] = promising_asin.loc[i]['impression']
        temp['click'] = promising_asin.loc[i]['click']
        temp['spend'] = promising_asin.loc[i]['spend']
        temp['sales'] = promising_asin.loc[i]['sales']
        perfect_table = perfect_table.append(temp,ignore_index = True)
        continue
    else:
        category = spider_g.iloc[spider_g.index.get_level_values('asin') == i].index.get_level_values('category')[0]
        sub_category = spider_g.iloc[spider_g.index.get_level_values('asin') == i].index.get_level_values('sub_category')[0]
        temp['asin'] = i
        temp['shop_name'] = promising_asin.loc[i]['shop_name']
        temp['performance'] = promising_asin.loc[i]['performance']
        temp['impression'] = promising_asin.loc[i]['impression']
        temp['click'] = promising_asin.loc[i]['click']
        temp['spend'] = promising_asin.loc[i]['spend']
        temp['sales'] = promising_asin.loc[i]['sales']
        temp['price'] = spider_g.loc[(i,category,sub_category),'price']
        temp['coupon'] = spider_g.loc[(i,category,sub_category),'coupon']
        temp['category'] = category
        temp['category_rank'] = spider_g.loc[(i,category,sub_category),'category_rank']
        temp['sub_category'] = sub_category
        temp['sub_category_rank'] = spider_g.loc[(i,category,sub_category),'sub_category_rank']
        temp['review'] = spider_g.loc[(i,category,sub_category),'review']
        temp['star'] = spider_g.loc[(i,category,sub_category),'star']
        temp['ask_num'] = spider_g.loc[(i,category,sub_category),'ask_num']
        perfect_table = perfect_table.append(temp,ignore_index = True)
print(manual_needed)

['B07J3BRYMF' 'B07J682X3D' 'B07JB4JMWF' 'B07JB4XMCC' 'B07JC3P9HH'
 'B07JC83QFN' 'B07JC8BTFT' 'B07JVBLQD2' 'B07P6WKK9M' 'B07PJZWWC5'
 'B07PNNJFN3' 'B07PPD56SM' 'B07PRNTZK3' 'B07QQY5G8Q' 'B07QX3PJ85'
 'B07VKMPJGC' 'B07XF864JZ' 'B07Z1RRY9G' 'B07ZJMB9ZM' 'B081JWF1T9'
 'B081PY41FJ' 'B0832MJGDC' 'B083Z5J4W2' 'B085C34C1Z' 'B087CW5PYT'
 'B08B4F79D4' 'B08DR756WC' 'B08DXT5VFT' 'B08F26VKL3' 'B08F2D58GL'
 'B08GCKX8ZL' 'B08GFGBPDK' 'B08GKB6DH5' 'B08GKBFCSF' 'B08GKBG9W4'
 'B08H1K8Q4Z' 'B08H1WL419' 'B08H4T346L' 'B08HCN4RDF' 'B08HMKDLW5'
 'B08HRPV2VZ' 'B08HVPJ4CR']

In [8]:
print(perfect_table[:10])

         asin shop_name  performance impression click  spend   sales    price  \
0  B0172W2D6M  tangkula     5.454545      99922   965  38125  326576  139.990
1  B01M641PUR  tangkula     3.600000     136578   515  22990  241967   79.990
2  B01MUICHSX  tangkula     3.818182      89941   343  11611   90985   47.990
3  B01N0XMGQT  tangkula     3.882353     104837   427  32649  337778  152.990
4  B01N25WLAG  tangkula     4.285714      24924   162   6554  108988  109.990
5  B01N29US2V  tangkula     2.250000     139649   489  12158   91787   65.990
6  B0744B7PTW  tangkula     4.583333     115117   433  11024  175989  159.990
7  B074SD5RX2  tangkula     7.916667     190496   353  34535  303981  159.990
8  B0757J17ZV  tangkula     2.307692      31655   129   5020   22394   14.995
9  B07BHG8643  tangkula    15.000000     340652  1132  66509  200766   65.990

   coupon             category  category_rank sub_category  sub_category_rank  \
0   7.000  Patio Lawn & Garden        14113.5          Nix                0.0
1   0.000    Sports & Outdoors        19457.5          Nix                0.0
2   0.050       Home & Kitchen        83984.5          Nix                0.0
3   8.000    Sports & Outdoors        21737.0          Nix                0.0
4   0.000  Patio Lawn & Garden        10048.5          Nix                0.0
5   0.025       Home & Kitchen        81164.5          Nix                0.0
6   8.000       Home & Kitchen        43569.5          Nix                0.0
7   8.000    Sports & Outdoors        31837.0          Nix                0.0
8   0.000       Home & Kitchen       181951.0          Nix                0.0
9   0.050       Home & Kitchen        25911.5          Nix                0.0

   review  star  ask_num
0   343.5  3.20     46.0
1   234.0  4.50     29.0
2   286.5  4.05      0.0
3   290.0  4.60     67.0
4   256.0  4.00      0.0
5   532.0  4.20      0.0
6   780.5  4.40      0.0
7   155.0  4.60     25.0
8    31.0  4.50      0.0
9  1111.5  4.60      0.0

In [10]:
#将整合完成的表格写入csv中
with open('perfect_table.csv', 'a', encoding='utf-8',newline="") as f:
        perfect_table.to_csv(f, mode='a+', index=False,  header = True)

perfect_table_result = pd.read_csv('perfect_table.csv')
print(perfect_table_result)
# 关闭文件
f.close()#只有在文件关闭状态下才不会报错

           asin shop_name  performance  impression  click  spend   sales  \
0    B0172W2D6M  tangkula     5.454545       99922    965  38125  326576
1    B01M641PUR  tangkula     3.600000      136578    515  22990  241967
2    B01MUICHSX  tangkula     3.818182       89941    343  11611   90985
3    B01N0XMGQT  tangkula     3.882353      104837    427  32649  337778
4    B01N25WLAG  tangkula     4.285714       24924    162   6554  108988
..          ...       ...          ...         ...    ...    ...     ...
306  B08HGQ2CRM     gymax     4.333333       72736    319  23288  285987
307  B08HMKDLW5   goflame     2.000000       21519     72   1777   11198
308  B08HRPV2VZ   goflame     4.000000        2189     34    881   27998
309  B08HRSR399     gymax     2.800000      216117    987  30580  293986
310  B08HVPJ4CR   goflame     2.000000       10113     54   1348    9999

      price  coupon             category  category_rank sub_category  \
0    139.99    7.00  Patio Lawn & Garden        14113.5          Nix
1     79.99    0.00    Sports & Outdoors        19457.5          Nix
2     47.99    0.05       Home & Kitchen        83984.5          Nix
3    152.99    8.00    Sports & Outdoors        21737.0          Nix
4    109.99    0.00  Patio Lawn & Garden        10048.5          Nix
..      ...     ...                  ...            ...          ...
306  219.99    0.00    Sports & Outdoors        24062.0          Nix
307     NaN     NaN                  NaN            NaN          NaN
308     NaN     NaN                  NaN            NaN          NaN
309  209.99   20.00         Toys & Games        33092.5          Nix
310     NaN     NaN                  NaN            NaN          NaN

     sub_category_rank  review  star  ask_num
0                  0.0   343.5  3.20     46.0
1                  0.0   234.0  4.50     29.0
2                  0.0   286.5  4.05      0.0
3                  0.0   290.0  4.60     67.0
4                  0.0   256.0  4.00      0.0
..                 ...     ...   ...      ...
306                0.0    19.0  4.60      7.0
307                NaN     NaN   NaN      NaN
308                NaN     NaN   NaN      NaN
309                0.0     1.0  5.00      6.0
310                NaN     NaN   NaN      NaN

[311 rows x 16 columns]